INSERT
{
  GRAPH <http://www.imn.htwk-leipzig.de/gjenschm/ontologies/internationalWineAndFood/#>
  {
    ?recipe iwf:hasCuisine ?cuisine
  }
}
USING <http://www.imn.htwk-leipzig.de/gjenschm/ontologies/cookbook/#>
USING <http://www.imn.htwk-leipzig.de/gjenschm/ontologies/wineToMatch/#>
WHERE
{
  {
    ?cuisine a wtm:Cuisine ;
             rdfs:label "British"
  }
  .
  {
    {
      ?recipe a cookbook:Recipe ;          
              dcterms:subject ?cat
    }
    OPTIONAL 
    { 
      { ?cat skos:broader* ?superCat } .
      { ?superCat rdfs:label ?catLabel } 
    }
  }
  FILTER 
  (
    contains(lcase(?catLabel),lcase("English")) ||
    contains(lcase(?catLabel),lcase("North Irish")) ||
    contains(lcase(?catLabel),lcase("Welsh")) ||
    contains(lcase(?catLabel),lcase("Scottish"))
  )
}