INSERT
{
  GRAPH <http://www.imn.htwk-leipzig.de/gjenschm/ontologies/internationalWineAndFood/#>
  {
    ?recipe iwf:hasIngredient wtm:Shellfish
  }
}
USING <http://www.imn.htwk-leipzig.de/gjenschm/ontologies/cookbook/#>
USING <http://www.imn.htwk-leipzig.de/gjenschm/ontologies/wineToMatch/#>
WHERE
{
  {
    ?ingredient a wtm:Ingredient ;
                rdfs:label "Shellfish"
  }
  .
  {
    {
      ?recipe a cookbook:Recipe ;          
              dcterms:subject ?cat
    }
    OPTIONAL 
    { 
      { ?cat skos:broader* ?superCat } .
      { ?superCat rdfs:label ?catLabel } 
    }
  }
  FILTER 
  (
    contains(lcase(?catLabel),lcase("Oyster")) || 
    contains(lcase(?catLabel),lcase("Clam")) ||
    contains(lcase(?catLabel),lcase("Conch")) ||
    contains(lcase(?catLabel),lcase("Crab")) ||
    contains(lcase(?catLabel),lcase("Crawfish")) ||
    contains(lcase(?catLabel),lcase("Lobster")) ||
    contains(lcase(?catLabel),lcase("Mussel")) ||
    contains(lcase(?catLabel),lcase("Scallop")) ||
    contains(lcase(?catLabel),lcase("Shrimp")) ||
    contains(lcase(?catLabel),lcase("Snail")) ||
    contains(lcase(?catLabel),lcase("Squid"))
  )
}